// src/types/database.ts
// Database types — will be auto-generated by `npx supabase gen types typescript`
// These are placeholder types matching our schema for development

import type { CancellationKind } from '@/lib/voidReasons'

export type OrderStatus ='pending' | 'confirmed' | 'preparing' | 'ready' | 'delivered' | 'cancelled'
// Per-line-item lifecycle. Enables Select Item(s)/Select All + partial ready/served.
// orders.status is the rolled-up aggregate of its items' statuses.
export type OrderItemStatus = 'pending' | 'preparing' | 'ready' | 'served' | 'cancelled'
export type SessionStatus = 'active' | 'closed' | 'expired'
export type PaymentStatus = 'unpaid' | 'pending' | 'paid' | 'refunded' | 'failed'
// 'owner' has no corresponding row in the `roles` table (custom_access_token_hook
// derives app_role from roles.name) — it's kept here because auth.ts and the
// billing actions already branch on it defensively for legacy/edge-case JWTs.
// finance_manager/accountant/receptionist were added for the Finance module's
// permission structure (see finance_role_permissions) — they exist as real
// `roles` rows but are not yet granted /admin/finance access (still gated to
// super_admin/manager only); that enforcement wiring is a later phase.
export type RoleName = 'super_admin' | 'manager' | 'kitchen' | 'waiter' | 'cashier' | 'bartender' | 'customer' | 'owner' | 'finance_manager' | 'accountant' | 'receptionist'

// Re-exported so the DB row types below can name it without every consumer
// importing from two places. The station registry itself lives in lib/stations.
import type { StationKind } from '@/lib/stations'
export type { StationKind }

// Roles that require the restaurant's financeEnabled feature (enterprise
// finance plan) before they can be assigned or invited.
export const FINANCE_GATED_ROLES: readonly RoleName[] = ['finance_manager', 'accountant', 'receptionist']
export type PricingRuleType = 'percentage_off' | 'fixed_price' | 'amount_off'
export type PromoType = 'percentage_off' | 'amount_off' | 'free_item' | 'bogo'
export type LoyaltyTier = 'bronze' | 'silver' | 'gold' | 'platinum'
export type ServiceRequestType = 'call_waiter' | 'request_bill' | 'need_water' | 'clean_table' | 'other' | 'open_session'
export type ServiceRequestStatus = 'pending' | 'acknowledged' | 'completed' | 'cancelled'
export type SplitType = 'by_seat' | 'even' | 'custom' | 'full'
export type TakeoutStatus = 'placed' | 'confirmed' | 'preparing' | 'ready_for_pickup' | 'picked_up' | 'cancelled'
export type IngredientMovementType = 'purchase' | 'usage' | 'waste' | 'adjustment' | 'transfer'

export interface Role {
    id: number
    name: RoleName
    description: string | null
}

export type SubscriptionTier = 'free' | 'basic' | 'premium' | 'platinum' | 'enterprise'
// 'trialing' = inside the 14-day signup trial. It is a distinct status from
// 'active' because a trial running out is not a billing failure: it downgrades
// the tenant to Free rather than suspending them (see lib/trial.ts).
export type SubscriptionStatus = 'active' | 'trialing' | 'past_due' | 'suspended' | 'cancelled'
export type PaymentMethod = 'qr_scan' | 'esewa' | 'khalti' | 'fonepay' | 'cash' | 'card'

export interface Restaurant {
    id: string
    owner_id: string | null
    name: string
    slug: string
    logo_url: string | null
    is_active: boolean
    is_suspended: boolean
    created_at: string
    updated_at: string
    // Nepal business fields
    contact_phone: string | null
    contact_email: string | null
    address: string | null
    pan_number: string | null
    vat_registered: boolean
    vat_number: string | null
    slogan: string | null
    telephone: string | null
    business_type: string | null
    latitude: number | null
    longitude: number | null
    payment_qr_url: string | null
    payment_qr_label: string
    qr_bank_account_id: string | null
    // SaaS fields
    custom_domain: string | null
    subscription_tier: SubscriptionTier
    subscription_status: SubscriptionStatus
    subscription_expires_at: string | null
    /** When the signup trial ends/ended. Kept after the downgrade clears
     *  subscription_expires_at, so NULL means "never had a trial". */
    trial_ends_at: string | null
    stripe_customer_id: string | null
    stripe_subscription_id: string | null
    // Subscription limits
    max_staff: number
    max_menu_items: number
    max_tables: number
    physical_menu_urls: string[] | null
    allowed_ips: string | null
}

export interface Department {
    id: string
    restaurant_id: string
    name: string
    description: string | null
    created_at: string
}

export interface User {
    id: string
    restaurant_id: string
    department_id: string | null
    full_name: string
    avatar_url: string | null
    phone: string | null
    emergency_contact: string | null
    address: string | null
    role_id: number
    is_active: boolean
    deleted_at: string | null
    created_at: string
    updated_at: string
    // Joined fields
    roles?: Role
    departments?: Department
}

export type TableStatus = 'available' | 'dirty' | 'reserved'

export interface Table {
    id: string
    restaurant_id: string
    label: string
    qr_token: string
    nfc_uid: string | null
    capacity: number | null
    is_active: boolean
    table_status: TableStatus
    // The hotel room this table is the in-room QR for. Null for dining tables.
    // This is the keyed room↔order bridge the folio matches on.
    room_id?: string | null
    // Cleaning ownership: set when a waiter claims a dirty table ("I am going");
    // only this waiter may mark it clean. Null when available/occupied/unclaimed.
    cleaning_claimed_by?: string | null
    cleaning_claimed_at?: string | null
    created_at: string
}

// Restaurant-level printer config (see the printers table migration). role maps
// a printer to what it prints: 'kot' kitchen tickets, 'bot' bar tickets, 'bill'
// the customer invoice. Network printers carry ip_address + port; usb printers
// are still selected per-device (printerSettings.ts) and are the fallback.
export type PrinterType = 'network' | 'usb'
export type PrinterConfigRole = 'kot' | 'bot' | 'bill'
export type PaperWidth = '58mm' | '80mm'

export interface Printer {
    id: string
    restaurant_id: string
    name: string
    printer_type: PrinterType
    ip_address: string | null
    port: number
    role: PrinterConfigRole
    paper_width: PaperWidth
    copies: number
    is_active: boolean
    is_default: boolean
    created_by?: string | null
    created_at: string
    updated_at: string
}

export interface MenuCategory {
    id: string
    restaurant_id: string
    name: string
    sort_order: number
    is_visible: boolean
    emoji?: string | null
    image_url?: string | null
    /** Default station for items in this category. */
    station?: StationKind
}

export interface MenuItemVariation {
    id: string
    menu_item_id: string
    name: string
    price: number
    is_available: boolean
    image_url: string | null
    created_at: string
}

export interface MenuItem {
    id: string
    restaurant_id: string
    category_id: string | null
    name: string
    description: string | null
    price: number
    image_url: string | null
    is_available: boolean
    stock_count: number | null
    preparation_min: number | null
    allergens: string[] | null
    tags: string[] | null
    is_combo?: boolean
    estimated_cost_price?: number | null
    /** Overrides the category's station. Null/undefined = inherit it. */
    station?: StationKind | null
    created_at: string
    updated_at: string
    // Joined fields
    menu_categories?: MenuCategory
    modifier_groups?: ModifierGroup[]  // alias used client-side
    menu_item_modifier_groups?: ModifierGroup[]  // actual DB relation name
    variations?: MenuItemVariation[]
}

export interface ModifierGroup {
    id: string
    menu_item_id: string
    name: string
    min_selections: number
    max_selections: number
    sort_order: number
    created_at: string
    /** Retired, but kept so past bills still name what they charged for. Never shown on a menu. */
    is_archived: boolean
    // Joined fields
    modifiers?: Modifier[]  // alias used client-side
    menu_item_modifiers?: Modifier[]  // actual DB relation name
}

export interface Modifier {
    id: string
    group_id: string
    name: string
    price_adjustment: number
    /** Temporarily off (out of stock tonight) — still editable by the manager. */
    is_available: boolean
    sort_order: number
    created_at: string
    /** Removed for good. Distinct from is_available; see the ModifierGroup note. */
    is_archived: boolean
}

export interface Session {
    id: string
    table_id: string
    restaurant_id: string
    opened_by: string | null
    session_token: string
    status: SessionStatus
    opened_at: string
    closed_at: string | null
    expires_at: string
    guest_count: number | null
    max_seats: number
    /** Which "cover" at the table this session belongs to (1-based). A table's
     *  original single-session behavior is seat 1; a waiter can open additional
     *  seats (2..capacity) so unrelated parties sharing one table each get their
     *  own independent order and bill. */
    seat_number: number
    notes: string | null
    discount_amount: number
    discount_reason: string | null
    discount_applied_by: string | null
    discount_applied_at: string | null
    booking_id: string | null
    // Joined fields
    tables?: Table
    seats?: SessionSeat[]
}

export interface SessionSeat {
    id: string
    session_id: string
    seat_number: number
    label: string | null
    device_fingerprint: string | null
    created_at: string
}

export interface Order {
    id: string
    session_id: string
    restaurant_id: string
    customer_note: string | null
    status: OrderStatus
    subtotal_amount: number
    service_charge_amount: number
    tax_amount: number
    tip_amount: number
    discount_amount: number
    total_amount: number
    payment_status: PaymentStatus
    payment_method: 'cash' | 'card' | 'mobile' | 'split' | null
    stripe_payment_intent_id: string | null
    promo_code_id: string | null
    loyalty_member_id: string | null
    refunded_amount: number
    client_request_id: string | null
    // Mode 2 (waiter confirmation): true while a placed order is waiting for a
    // waiter to confirm the customer is seated; the kitchen hides these until then.
    needs_confirmation?: boolean
    /** Sold straight over the counter — cigarettes, a bottle off the shelf — so
     *  no station ticket printed and no station ever queued it. Its lines are
     *  written already served. Billing and stock are unaffected. */
    no_kot?: boolean
    cancellation_reason?: string | null
    /** Whether this was written off as a mistake or given away deliberately. See lib/voidReasons.ts. */
    cancellation_kind?: CancellationKind | null
    /** Structured counterpart to cancellation_reason — the part a report can group by. */
    cancellation_reason_code?: string | null
    /** Staff-only refund audit trail. Deliberately not customer_note, which the guest writes and reads. */
    refund_reason?: string | null
    refund_reason_code?: string | null
    placed_at: string
    confirmed_at: string | null
    ready_at: string | null
    delivered_at: string | null
    paid_at: string | null
    seat_id: string | null
    claimed_by: string | null
    claimed_at: string | null
    /** Staff member who settled this order at checkout; null until it's paid. */
    cashier_id?: string | null
    // Joined fields
    order_items?: OrderItem[]
    sessions?: Session
    session_seats?: SessionSeat
    order_promos?: OrderPromo[]
}

export interface OrderItem {
    id: string
    order_id: string
    menu_item_id: string
    /** Chosen variation (half/full plate, size, …); null for a plain item. */
    menu_item_variation_id?: string | null
    quantity: number
    unit_price: number
    special_request: string | null
    status: OrderItemStatus
    // True while this line is a QR self-order item awaiting cashier review
    // in the Cashier "Order Confirmation" panel — hidden from the kitchen
    // and stock is not yet deducted until a cashier confirms it.
    needs_confirmation: boolean
    // Per-dish chef ownership: set when a chef clicks Cook; only this chef may
    // mark the dish ready. Null until cooking starts (or for legacy rows).
    claimed_by?: string | null
    claimed_at?: string | null
    /** Where this line is made. Resolved and frozen when the line is written. */
    station?: StationKind
    // When a print station claimed this line for its ticket. Null means the
    // line is still outstanding, so any station that connects will print it —
    // this is what stops a ticket depending on a tab being subscribed at the
    // instant the order landed. Claimed atomically; see printClaims.ts.
    kot_printed_at?: string | null
    created_at: string
    // Who took this line off the bill, why, and when. This is the one place a
    // single plate can quietly leave a bill, so the evidence lives on the row
    // itself rather than only in the audit log.
    cancellation_kind?: CancellationKind | null
    cancellation_reason?: string | null
    cancellation_reason_code?: string | null
    cancelled_by?: string | null
    cancelled_at?: string | null
    // Joined fields
    menu_items?: MenuItem
    order_item_modifiers?: OrderItemModifier[]
}

export interface OrderItemModifier {
    id: string
    order_item_id: string
    modifier_id: string
    modifier_name: string
    price_adjustment: number
    created_at: string
}

export interface Settings {
    id: string
    restaurant_id: string
    theme: {
        primaryColor: string
        secondaryColor: string
        accentColor?: string
        fontFamily: string
        borderRadius: string
        menuLayout: string
    }
    features: {
        tipsEnabled: boolean
        feedbackEnabled: boolean
        geofenceEnabled: boolean
        geofenceRadiusMeters: number
    }
    features_v2: {
        loyaltyEnabled: boolean
        promosEnabled: boolean
        takeoutEnabled: boolean
        // Whether the dine-in/table/QR ordering pathway is offered at all.
        // false for delivery-only operations (Cloud Kitchen) — hides Table
        // Layout nav, the "select your table" customer entry point, and
        // session/waiter dine-in UI. See lib/businessMode.ts.
        dineInEnabled: boolean
        multiLanguageEnabled: boolean
        serviceRequestsEnabled: boolean
        splitBillingEnabled: boolean
        dynamicPricingEnabled: boolean
        ingredientTrackingEnabled: boolean
        staffShiftsEnabled: boolean
        feedbackEnabled: boolean
        // Customers can request a waiter to open their table session (Phase 3)
        selfOrderRequestEnabled?: boolean
        // When true, a waiter must open a table session before guests can order.
        // When false/undefined (default), sessions auto-open on QR scan (self-service).
        waiterSessionEnabled?: boolean
        // When true (Mode 2 / low plans), placed dine-in orders wait for a waiter to
        // confirm before the kitchen sees them; stock is deducted on confirm. When
        // false (Mode 1 / premium), orders go straight to the kitchen at placement.
        waiterOrderConfirmation?: boolean
        // Manager-configured one-tap "quick serve" items a customer can request
        // (water, cold drink, tissue…). Each request goes to the waiter feed.
        quickServeItems?: string[]
        defaultTaxRate: number
        currency: string
        currencySymbol: string
        // Nepal-specific
        nepalPayEnabled: boolean
        vatEnabled: boolean
        serviceChargeEnabled?: boolean
        serviceChargeRate?: number
        phoneOtpEnabled: boolean
        /**
         * @deprecated Superseded by the per-user calendar toggle (the
         * kkkhane-calendar cookie, see lib/calendar.ts). Bikram Sambat now
         * leads by default for everyone and each user flips their own
         * preference, so nothing reads this. Kept so stored settings rows
         * still parse; safe to drop in a later migration.
         */
        bsDateEnabled: boolean
        // Notification
        notificationSoundUrl?: string | null
        financeEnabled?: boolean
        // In-room service: when true, a hotel room's QR requires the guest to
        // confirm the phone on their booking, then surfaces a "Call for Service"
        // tel: button to the reception number below. Off = today's self-service.
        roomServiceCallEnabled?: boolean
        // Reception / room-service phone the "Call for Service" button dials.
        receptionPhone?: string | null
        printInvoiceEnabled?: boolean
        generateInvoiceEnabled?: boolean
        staffManagementEnabled?: boolean
        tableManagementEnabled?: boolean
        irdSyncEnabled?: boolean
        manualEntryEnabled?: boolean
        printBillEnabled?: boolean
        showInvoiceEnabled?: boolean
        kotEnabled?: boolean
        kdsEnabled?: boolean
        roomServiceChargeEnabled?: boolean
        roomServiceChargeRooms?: string[]
    }
    business_hours: BusinessHours | null
    updated_at: string
}

// Per-day opening hours. Keys are lowercase weekday names (monday…sunday).
export interface DayHours {
    open: string   // "HH:MM" 24h
    close: string  // "HH:MM" 24h
    closed: boolean
}
export type BusinessHours = Record<string, DayHours>

// ============================================================
// Dynamic Pricing & Happy Hours
// ============================================================
export interface PricingRule {
    id: string
    restaurant_id: string
    name: string
    description: string | null
    rule_type: PricingRuleType
    value: number
    applies_to_item_id: string | null
    applies_to_category_id: string | null
    applies_to_all: boolean
    days_of_week: number[]
    start_time: string
    end_time: string
    valid_from: string | null
    valid_until: string | null
    is_active: boolean
    priority: number
    created_at: string
    // Joined fields
    menu_items?: MenuItem
    menu_categories?: MenuCategory
}

// ============================================================
// Promo Codes & Discounts
// ============================================================
export interface PromoCode {
    id: string
    restaurant_id: string
    code: string
    description: string | null
    promo_type: PromoType
    value: number
    free_item_id: string | null
    bogo_buy_item_id: string | null
    bogo_get_item_id: string | null
    min_order_amount: number
    max_discount_amount: number | null
    max_uses: number | null
    max_uses_per_customer: number
    current_uses: number
    valid_from: string
    valid_until: string | null
    is_active: boolean
    created_at: string
}

export interface OrderPromo {
    id: string
    order_id: string
    promo_code_id: string
    code_used: string
    discount_amount: number
    created_at: string
}

// ============================================================
// CRM & Loyalty Program
// ============================================================
export interface LoyaltyMember {
    id: string
    restaurant_id: string
    auth_user_id: string | null
    phone: string | null
    email: string | null
    display_name: string | null
    points_balance: number
    lifetime_points: number
    lifetime_spend: number
    tier: LoyaltyTier
    visit_count: number
    last_visit_at: string | null
    created_at: string
    updated_at: string
}

export interface LoyaltyConfig {
    id: string
    restaurant_id: string
    points_per_dollar: number
    redemption_threshold: number
    redemption_value: number
    silver_threshold: number
    gold_threshold: number
    platinum_threshold: number
    birthday_bonus_points: number | null
    signup_bonus_points: number | null
    is_active: boolean
    updated_at: string
}

export interface LoyaltyTransaction {
    id: string
    member_id: string
    order_id: string | null
    type: 'earn' | 'redeem' | 'bonus' | 'adjustment' | 'expire'
    points: number
    description: string | null
    created_at: string
}

// ============================================================
// Ingredient-Level Inventory & Recipe Management
// ============================================================
export interface Ingredient {
    id: string
    restaurant_id: string
    name: string
    unit: string
    stock_quantity: number
    reorder_level: number | null
    cost_per_unit: number
    supplier: string | null
    category_id?: string | null
    is_active: boolean
    updated_at: string
    created_at: string
}

export interface Recipe {
    id: string
    menu_item_id: string
    ingredient_id: string
    quantity_needed: number
    created_at: string
    // Joined fields
    ingredients?: Ingredient
}

export interface IngredientMovement {
    id: string
    ingredient_id: string
    movement_type: IngredientMovementType
    quantity: number
    reference_id: string | null
    notes: string | null
    performed_by: string | null
    created_at: string
    // Joined fields
    ingredients?: Ingredient
    users?: User
}

// ============================================================
// EOD Z-Reports
// ============================================================
export interface EodReport {
    id: string
    restaurant_id: string
    report_date: string
    total_orders: number
    total_revenue: number
    total_tax: number
    total_tips: number
    total_discounts: number
    net_revenue: number
    cash_total: number
    card_total: number
    total_voids: number
    total_refunds: number
    total_cancelled: number
    total_cancellation_cost: number
    avg_order_value: number
    total_cogs: number
    gross_profit: number
    unverified_orders: number
    closed_by: string | null
    notes: string | null
    created_at: string
}

// ============================================================
// Service Requests ("Call Waiter")
// ============================================================
export interface ServiceRequest {
    id: string
    session_id: string | null
    table_id: string | null
    restaurant_id: string
    request_type: ServiceRequestType
    message: string | null
    status: ServiceRequestStatus
    acknowledged_by: string | null
    completed_at: string | null
    created_at: string
    // Joined fields
    sessions?: Session
    users?: User  // acknowledged_by
}

// ============================================================
// Split Billing
// ============================================================
export interface BillSplit {
    id: string
    session_id: string
    split_type: SplitType
    total_amount: number
    split_count: number
    created_at: string
    // Joined fields
    bill_split_items?: BillSplitItem[]
}

export interface BillSplitItem {
    id: string
    bill_split_id: string
    seat_id: string | null
    label: string | null
    amount: number
    tax_amount: number
    tip_amount: number
    total_amount: number
    payment_status: PaymentStatus
    stripe_payment_intent_id: string | null
    paid_at: string | null
    created_at: string
}

// ============================================================
// Multi-Language (i18n)
// ============================================================
export interface SupportedLanguage {
    id: string
    restaurant_id: string
    language_code: string
    language_name: string
    is_default: boolean
    is_active: boolean
    sort_order: number
    created_at: string
}

export interface Translation {
    id: string
    restaurant_id: string
    language_code: string
    entity_type: 'menu_item_name' | 'menu_item_description' | 'category_name' | 'modifier_group_name' | 'modifier_name' | 'restaurant_name'
    entity_id: string
    translated_text: string
    created_at: string
    updated_at: string
}

// ============================================================
// Takeout / Order-Ahead
// ============================================================
export interface TakeoutOrder {
    id: string
    restaurant_id: string
    loyalty_member_id: string | null
    customer_name: string
    customer_phone: string
    customer_email: string | null
    pickup_time: string
    estimated_prep_minutes: number | null
    status: TakeoutStatus
    items: CartItem[]  // JSONB snapshot
    subtotal_amount: number
    service_charge_amount: number
    tax_amount: number
    total_amount: number
    payment_status: PaymentStatus
    stripe_payment_intent_id: string | null
    promo_code_id: string | null
    discount_amount: number
    customer_note: string | null
    kitchen_note: string | null
    placed_at: string
    confirmed_at: string | null
    ready_at: string | null
    picked_up_at: string | null
    cancelled_at: string | null
    // Online delivery (order_type='delivery'): address + the verification code the
    // customer reads back to the delivery staff. Null/undefined for takeaway.
    order_type?: 'dine_in' | 'takeout' | 'delivery'
    delivery_address?: string | null
    delivery_verification_code?: string | null
}

// ============================================================
// Staff Time & Attendance
// ============================================================
export interface StaffShift {
    id: string
    user_id: string
    restaurant_id: string
    clock_in: string
    clock_out: string | null
    hours_worked: number | null
    break_start: string | null
    break_end: string | null
    break_minutes: number
    notes: string | null
    approved_by: string | null
    is_approved: boolean
    created_at: string
    // Joined fields
    users?: User
}

// Cart types (client-side only)
export interface CartItemModifier {
    modifierId: string
    name: string
    priceAdjustment: number
}

export interface CartItem {
    menuItemId: string
    name: string
    price: number
    quantity: number
    specialRequest?: string
    imageUrl?: string
    modifiers?: CartItemModifier[]
    variationId?: string
    variationName?: string
}

// ============================================================
// Nepal Payment Verification (QR-based)
// ============================================================
export interface PaymentVerification {
    id: string
    restaurant_id: string
    order_id: string | null
    takeout_order_id: string | null
    amount: number
    payment_method: PaymentMethod
    customer_claimed_at: string
    staff_verified: boolean
    staff_verified_by: string | null
    staff_verified_at: string | null
    staff_rejected: boolean
    rejection_reason: string | null
    reference_code: string | null
    screenshot_url: string | null
    created_at: string
}

// ============================================================
// SaaS Subscription Plans
// ============================================================
export interface SubscriptionPlan {
    id: string
    name: string
    price_monthly: number
    price_yearly: number
    currency: string
    max_menu_items: number
    max_staff: number
    max_tables: number
    max_orders_per_month: number | null
    features_included: Record<string, boolean>
    is_active: boolean
    created_at: string
}

// ============================================================
// Invoice Sequence (IRD compliance)
// ============================================================
export interface InvoiceSequence {
    restaurant_id: string
    last_sequence: number  // atomically incremented; format: INV-YYYY-00001
}

// ============================================================
// Phone OTP Token
// ============================================================
export interface PhoneOtpToken {
    id: string
    phone: string
    otp_code: string
    purpose: 'login' | 'verify' | 'loyalty_signup'
    restaurant_id: string | null
    expires_at: string
    used: boolean
    created_at: string
}

// ============================================================
// Plan Limit Check Result
// ============================================================
export interface PlanLimitResult {
    allowed: boolean
    current?: number
    max?: number
    tier?: string
    reason: string
}
// ============================================================
// Restaurant Homepage Configuration
// ============================================================
export type HomepageTemplate = 'modern' | 'elegant' | 'vibrant' | 'minimal' | 'classic'

export interface HomepageConfig {
    id?: string
    restaurant_id: string
    template: HomepageTemplate
    
    // Hero Section
    hero_title: string
    hero_subtitle: string
    hero_image_url: string | null
    hero_video_url: string | null
    hero_cta_text: string
    
    // Theme Customization
    theme_primary: string
    theme_secondary: string
    theme_accent: string

    // Branding
    logo_url?: string | null
    // Restaurant name, hydrated by the GET route for the navbar/footer (not a column)
    restaurant_name?: string

    // Content Sections (JSONB)
    about?: {
        enabled: boolean
        title: string
        description: string
        image_url: string
    }
    features?: Array<{
        title: string
        description: string
    }>
    cta?: {
        enabled: boolean
        headline: string
        description: string
        button_text: string
    }
    gallery?: Array<{
        image_url: string
        caption?: string
        media_type?: 'image' | 'video'
    }>
    social?: {
        facebook?: string
        instagram?: string
        whatsapp?: string
        tiktok?: string
    }
    contact?: {
        enabled?: boolean
        review_link?: string
        // Free-text physical address (shown in the contact section); distinct
        // from map_address, which holds the Google Maps link.
        address?: string
        map_address?: string
        phone?: string
        email?: string
    }
    footer?: {
        enabled: boolean
        copyright: string
        social_links: Array<{
            platform: string
            url: string
        }>
    }

    // Metadata
    created_at?: string
    updated_at?: string
}

export const HOMEPAGE_TEMPLATES: Record<HomepageTemplate, {
    name: string
    description: string
    icon: string
}> = {
    modern: {
        name: 'Modern',
        description: 'Clean, minimal design with bold typography',
        icon: '✨'
    },
    elegant: {
        name: 'Elegant',
        description: 'Sophisticated design with premium feel',
        icon: '👑'
    },
    vibrant: {
        name: 'Vibrant',
        description: 'Colorful and energetic design',
        icon: '🎨'
    },
    minimal: {
        name: 'Minimal',
        description: 'Simplistic, distraction-free design',
        icon: '◻️'
    },
    classic: {
        name: 'Classic',
        description: 'Traditional, timeless restaurant style',
        icon: '🏛️'
    }
}

// ────────────────────────────────────────────────
// Hotel Types
// ────────────────────────────────────────────────

export type RoomStatus = 'available' | 'occupied' | 'dirty' | 'maintenance'
export type BookingStatus = 'pending' | 'checked_in' | 'checked_out' | 'cancelled'

export interface RoomType {
    id: string
    restaurant_id: string
    name: string
    description: string | null
    base_price: number
    capacity: number
    created_at: string
}

export interface Room {
    id: string
    restaurant_id: string
    room_number: string
    floor: string | null
    beds: number
    status: RoomStatus
    type_id: string | null
    notes: string | null
    is_active: boolean
    created_at: string
    room_types?: RoomType | null
}

// How a booking's advance was collected. Older rows predate the column and
// carry null; the API writes 'none' when no advance was paid.
export type AdvancePaymentMethod = 'cash' | 'qr_digital' | 'split' | 'none'

export interface Booking {
    id: string
    restaurant_id: string
    room_id: string
    guest_name: string
    guest_phone: string | null
    guest_email: string | null
    /** Address written at the desk. Null means it was never asked for. */
    guest_address?: string | null
    check_in: string
    check_out: string
    /** Total adults — kept as `adult_male + adult_female` for new bookings. */
    adults: number
    /**
     * Adult split. Both 0 on bookings made before this existed, where only the
     * `adults` total is known — render those as a plain total rather than
     * implying a breakdown that was never recorded.
     */
    adult_male: number
    adult_female: number
    children: number
    status: BookingStatus
    total_amount: number
    paid_amount: number
    payment_status: 'unpaid' | 'partial' | 'paid' | 'refunded'
    advance_payment_method: AdvancePaymentMethod | null
    notes: string | null
    created_at: string
    discount_amount: number
    discount_reason: string | null
    discount_applied_by: string | null
    discount_applied_at: string | null
    extra_hour_charge?: number
    /** Service charge the cashier set at checkout, replacing what the folio
     *  rules produce. Null means no override — recompute from the rules; 0
     *  means the charge was deliberately waived. */
    service_charge_override?: number | null
    /** Staff member who settled this stay at checkout; null while in house. */
    cashier_id?: string | null
    /** When the guest actually departed (settlement time). Null while in
     *  house, and on stays checked out before this column existed. */
    checked_out_at?: string | null
    /** When the guest actually checked in (room handover). Null for a still-
     *  pending reservation, and for stays checked in before this column
     *  existed. Auto-stamped — never set by hand. */
    checked_in_at?: string | null
    /** Staff member who checked the guest in — the walk-in creator or
     *  whoever clicked Check In. Null for anything checked in before this
     *  column existed. Auto-stamped — never set by hand. */
    checked_in_by?: string | null
    /** When this stay's bill was closed out. Stamped by every settlement, and
     *  kept at the first one if a stay settles more than once. Null means never
     *  settled — including a room that departed early and is still riding on a
     *  shared bill. "Paid but still in the room" is this set while `status` is
     *  not yet `checked_out`. */
    bill_settled_at?: string | null
    /** Guest asked for a parking space. Any fee is a `room_charges` row of type
     *  'parking', never an amount stored here. */
    parking_required?: boolean
    /** Vehicle registration taken at the desk. Can be set even when
     *  `parking_required` is false — a guest with a car but no reserved space. */
    parking_vehicle_no?: string | null
    rooms?: Room | null
}

/**
 * One room a stay has occupied. `to_ts` null marks the room the guest is in
 * now, which is also what bookings.room_id points at.
 *
 * Exists so a mid-stay move keeps its history: the folio bills each night at
 * the rate of the room actually occupied that night, instead of re-pricing the
 * whole stay at whatever room the booking happens to point at now.
 */
export interface BookingRoomStay {
    id: string
    restaurant_id: string
    booking_id: string
    room_id: string
    from_ts: string
    to_ts: string | null
    moved_by: string | null
    reason: string | null
    created_at: string
    rooms?: Room | null
}

export interface BookingPayment {
    id: string
    restaurant_id: string
    booking_id: string
    amount: number
    payment_method: string
    cash_amount?: number
    qr_amount?: number
    note: string | null
    created_at: string
    created_by?: string | null
}


// ─── Day Book ───────────────────────────────────────────────
export type DayBookSessionStatus = 'open' | 'closed'
export type DayBookEntryType = 'cash_in' | 'cash_out' | 'bank_in' | 'bank_out'
export type DayBookEntryCategory =
    | 'order_payment'
    | 'room_deposit'
    | 'booking_payment'
    | 'expense'
    | 'refund'
    | 'salary'
    | 'advance'
    | 'bank_deposit'
    | 'other'
    // Bank categories
    | 'qr_payment'
    | 'card'
    | 'transfer'
    | 'deposit'
    | 'withdrawal'
    | 'bank_charges'
    | 'transfer_out'

export interface DayBookSession {
    id: string
    restaurant_id: string
    date: string             // ISO date string YYYY-MM-DD
    opening_balance: number
    opening_bank_balance: number
    status: DayBookSessionStatus
    closed_at: string | null
    closed_by: string | null
    notes: string | null
    created_by: string | null
    created_at: string
    updated_at: string
}

export interface DayBookEntry {
    id: string
    session_id: string
    restaurant_id: string
    type: DayBookEntryType
    amount: number
    description: string
    category: DayBookEntryCategory
    reference_id: string | null
    bank_name: string | null
    created_by: string | null
    created_at: string
}

export interface DayBookTotals {
    total_cash_in: number
    total_cash_out: number
    closing_balance: number
}

// ─── Finance: Cash Management ──────────────────────────────
export type CashTransactionType = 'cash_in' | 'cash_out' | 'opening' | 'closing' | 'transfer_in' | 'transfer_out' | 'adjustment'
export type FinanceRecordStatus = 'draft' | 'posted' | 'void'
export type CashCountStatus = 'draft' | 'reconciled' | 'flagged'

export interface CashDrawer {
    id: string
    restaurant_id: string
    name: string
    location: string | null
    opening_balance: number
    is_active: boolean
    created_by: string | null
    created_at: string
    updated_at: string
}

export interface CashTransaction {
    id: string
    restaurant_id: string
    drawer_id: string
    type: CashTransactionType
    amount: number
    description: string
    counterparty_drawer_id: string | null
    shift_id: string | null
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    cash_drawers?: CashDrawer | null
}

export interface CashCount {
    id: string
    restaurant_id: string
    drawer_id: string
    counted_total: number
    expected_total: number | null
    variance: number | null
    denominations: Record<string, number> | null
    notes: string | null
    status: CashCountStatus
    counted_by: string | null
    created_at: string
    cash_drawers?: CashDrawer | null
}

// ─── Finance: Bank Management ──────────────────────────────
export type BankAccountType = 'bank' | 'wallet'
export type WalletProvider = 'esewa' | 'khalti' | 'fonepay' | 'connectips'
export type BankTransactionType = 'deposit' | 'withdrawal' | 'transfer_in' | 'transfer_out'
export type BankReconciliationStatus = 'draft' | 'reconciled' | 'flagged'

export interface BankAccount {
    id: string
    restaurant_id: string
    name: string
    account_type: BankAccountType
    wallet_provider: WalletProvider | null
    bank_name: string | null
    account_number: string | null
    opening_balance: number
    is_active: boolean
    deactivation_reason: string | null
    created_by: string | null
    created_at: string
    updated_at: string
}

export interface BankTransaction {
    id: string
    restaurant_id: string
    bank_account_id: string
    type: BankTransactionType
    amount: number
    description: string
    counterparty_account_id: string | null
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    bank_accounts?: BankAccount | null
}

export interface BankReconciliation {
    id: string
    restaurant_id: string
    bank_account_id: string
    statement_date: string
    statement_balance: number
    book_balance: number | null
    variance: number | null
    notes: string | null
    status: BankReconciliationStatus
    reconciled_by: string | null
    created_at: string
    bank_accounts?: BankAccount | null
}

// ─── Finance: Income & Expenses ────────────────────────────
export interface IncomeCategory {
    id: string
    restaurant_id: string
    name: string
    description: string | null
    is_active: boolean
    created_by: string | null
    created_at: string
}

export interface IncomeEntry {
    id: string
    restaurant_id: string
    category_id: string
    amount: number
    description: string
    bank_account_id: string | null
    cash_drawer_id: string | null
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    income_categories?: IncomeCategory | null
}

export interface ExpenseCategory {
    id: string
    restaurant_id: string
    name: string
    description: string | null
    is_active: boolean
    is_stock_category: boolean
    /** Main category this one nests under, or null for a top-level/main category. One level deep. */
    parent_id: string | null
    created_by: string | null
    created_at: string
}

export type ExpenseStatus = 'pending' | 'approved' | 'rejected' | 'paid'
export type RecurrenceInterval = 'weekly' | 'monthly' | 'quarterly' | 'yearly'

export interface Expense {
    id: string
    restaurant_id: string
    category_id: string
    amount: number
    description: string
    vendor_name: string | null
    bank_account_id: string | null
    cash_drawer_id: string | null
    // Set when a Day Book entry (Voucher, Cash/Bank Book expense) owns this
    // row; deleting that entry cascades this away. NULL when the expense was
    // created first and posted to the Day Book as a side effect.
    day_book_entry_id: string | null
    is_recurring: boolean
    recurrence_interval: RecurrenceInterval | null
    status: ExpenseStatus
    approved_by: string | null
    approved_at: string | null
    created_by: string | null
    created_at: string
    expense_categories?: ExpenseCategory | null
}

export interface ExpenseAttachment {
    id: string
    restaurant_id: string
    expense_id: string
    file_url: string
    file_name: string | null
    uploaded_by: string | null
    created_at: string
}

// ─── Finance: Receivables & Payables ───────────────────────
export interface CustomerCreditAccount {
    id: string
    restaurant_id: string
    loyalty_member_id: string | null
    customer_name: string
    customer_phone: string | null
    credit_limit: number
    is_active: boolean
    created_by: string | null
    created_at: string
}

export type ReceivableTransactionType = 'charge' | 'payment'

export interface ReceivableTransaction {
    id: string
    restaurant_id: string
    customer_credit_account_id: string
    type: ReceivableTransactionType
    amount: number
    description: string
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    customer_credit_accounts?: CustomerCreditAccount | null
}

/** A receivable transaction with the responsible staff member's name resolved
 *  from `created_by` — attached server-side, never stored. */
export type ReceivableTransactionWithCreator = ReceivableTransaction & { created_by_name: string | null }

export interface Supplier {
    id: string
    restaurant_id: string
    name: string
    contact_person: string | null
    phone: string | null
    email: string | null
    address: string | null
    category_id?: string | null
    is_active: boolean
    created_by: string | null
    created_at: string
    updated_at: string
}

export type SupplierBillStatus = 'unpaid' | 'partial' | 'paid'

export interface SupplierBill {
    id: string
    restaurant_id: string
    supplier_id: string
    bill_number: string | null
    amount: number
    description: string | null
    due_date: string | null
    status: SupplierBillStatus
    created_by: string | null
    created_at: string
    suppliers?: Supplier | null
}

export interface SupplierPayment {
    id: string
    restaurant_id: string
    supplier_id: string
    bill_id: string | null
    amount: number
    description: string | null
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    suppliers?: Supplier | null
    supplier_bills?: SupplierBill | null
}

// ─── Finance: Loans ─────────────────────────────────────────
export type LoanStatus = 'active' | 'closed'

export interface Loan {
    id: string
    restaurant_id: string
    lender_name: string
    principal_amount: number
    interest_rate: number | null
    start_date: string
    tenure_months: number | null
    notes: string | null
    status: LoanStatus
    created_by: string | null
    created_at: string
    updated_at: string
}

export interface LoanPayment {
    id: string
    restaurant_id: string
    loan_id: string
    amount: number
    principal_component: number | null
    interest_component: number | null
    payment_date: string
    status: FinanceRecordStatus
    created_by: string | null
    created_at: string
    loans?: Loan | null
}

export type LoanEmiStatus = 'pending' | 'paid' | 'overdue'

export interface LoanEmiSchedule {
    id: string
    restaurant_id: string
    loan_id: string
    installment_no: number
    due_date: string
    amount: number
    status: LoanEmiStatus
    created_at: string
    loans?: Loan | null
}

// ─── Finance: Budget ────────────────────────────────────────
export interface BudgetCategory {
    id: string
    restaurant_id: string
    name: string
    linked_expense_category_id: string | null
    linked_income_category_id: string | null
    is_active: boolean
    created_by: string | null
    created_at: string
}

export type BudgetPeriodType = 'monthly' | 'quarterly' | 'yearly'
export type BudgetStatus = 'draft' | 'active' | 'closed'

export interface Budget {
    id: string
    restaurant_id: string
    name: string
    period_type: BudgetPeriodType
    start_date: string
    end_date: string
    status: BudgetStatus
    created_by: string | null
    created_at: string
}

export interface BudgetLine {
    id: string
    restaurant_id: string
    budget_id: string
    category_id: string
    planned_amount: number
    created_at: string
    budget_categories?: BudgetCategory | null
}

// ─── Finance: Tax ───────────────────────────────────────────
export type TaxType = 'vat' | 'pan' | 'other'

export interface TaxConfiguration {
    id: string
    restaurant_id: string
    name: string
    tax_type: TaxType
    rate_percent: number | null
    is_active: boolean
    created_by: string | null
    created_at: string
}

export type TaxFilingStatus = 'draft' | 'filed'

export interface TaxFiling {
    id: string
    restaurant_id: string
    tax_configuration_id: string
    period_start: string
    period_end: string
    ird_reference: string | null
    notes: string | null
    status: TaxFilingStatus
    filed_by: string | null
    filed_at: string | null
    created_at: string
    tax_configurations?: TaxConfiguration | null
}

// ─── Finance: Administration ───────────────────────────────
export type AccountType = 'asset' | 'liability' | 'equity' | 'income' | 'expense'

export interface ChartOfAccount {
    id: string
    restaurant_id: string
    code: string
    name: string
    account_type: AccountType
    parent_id: string | null
    is_active: boolean
    created_by: string | null
    created_at: string
    updated_at: string
    parent?: ChartOfAccount | null
}

export type VoucherCategory = 'receipt' | 'payment' | 'journal' | 'contra'

export interface VoucherType {
    id: string
    restaurant_id: string
    name: string
    voucher_category: VoucherCategory
    prefix: string
    is_active: boolean
    created_by: string | null
    created_at: string
}

export type FinancePaymentMethodCategory = 'cash' | 'bank' | 'wallet'

export interface FinancePaymentMethod {
    id: string
    restaurant_id: string
    name: string
    category: FinancePaymentMethodCategory
    is_active: boolean
    created_by: string | null
    created_at: string
}

export interface ApprovalLevel {
    id: string
    restaurant_id: string
    name: string
    level_order: number
    min_amount: number
    max_amount: number | null
    role_required: string
    is_active: boolean
    created_by: string | null
    created_at: string
}

export type FiscalYearStatus = 'open' | 'closed'

export interface FiscalYear {
    id: string
    restaurant_id: string
    name: string
    start_date: string
    end_date: string
    is_current: boolean
    status: FiscalYearStatus
    created_at: string
}

export interface AccountingPeriod {
    id: string
    restaurant_id: string
    fiscal_year_id: string
    name: string
    start_date: string
    end_date: string
    status: FiscalYearStatus
    created_at: string
    fiscal_years?: FiscalYear | null
}

export type RoundingMode = 'nearest' | 'up' | 'down' | 'none'

export interface FinanceSettings {
    restaurant_id: string
    base_currency: string
    default_tax_rate: number
    fiscal_year_start_month: number
    rounding_mode: RoundingMode
    updated_at: string
}

// ─── Finance: Financial Event Engine (Phase 2, Step 1) ─────
export const FINANCIAL_EVENT_TYPES = [
    'RESTAURANT_SALE', 'HOTEL_CHECKOUT', 'BOOKING_ADVANCE',
    'INVENTORY_PURCHASE', 'SUPPLIER_PAYMENT', 'SALARY_PAYMENT',
    'CASH_DEPOSIT', 'CASH_WITHDRAWAL', 'BANK_TRANSFER',
    'EXPENSE_PAYMENT', 'OTHER_INCOME', 'LOAN_RECEIVED',
    'LOAN_REPAYMENT', 'OWNER_INVESTMENT', 'OWNER_WITHDRAWAL',
    'REFUND', 'ADJUSTMENT',
] as const
export type FinancialEventType = typeof FINANCIAL_EVENT_TYPES[number]

export const FINANCIAL_EVENT_STATUSES = ['PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'REVERSED'] as const
export type FinancialEventStatus = typeof FINANCIAL_EVENT_STATUSES[number]

export interface FinancialEvent {
    id: string
    event_code: string
    event_type: FinancialEventType
    source_module: string
    source_id: string | null
    restaurant_id: string
    branch_id: string | null
    business_date: string
    accounting_date: string
    amount: number
    currency: string
    payment_method_id: string | null
    customer_id: string | null
    supplier_id: string | null
    employee_id: string | null
    reference_number: string | null
    description: string | null
    metadata: Record<string, unknown> | null
    status: FinancialEventStatus
    retry_count: number
    created_by: string | null
    processed_at: string | null
    created_at: string
    updated_at: string
    suppliers?: Supplier | null
    finance_payment_methods?: FinancePaymentMethod | null
}

// ─── Audit Logs (existing table — src/lib/audit.ts) ────────
export interface AuditLog {
    id: string
    restaurant_id: string
    user_id: string | null
    action: string
    entity_type: string
    entity_id: string | null
    old_value: Record<string, unknown> | null
    new_value: Record<string, unknown> | null
    ip_address: string | null
    created_at: string
}

export interface FinanceRolePermission {
    id: string
    restaurant_id: string
    role_name: string
    module: string
    can_view: boolean
    can_create: boolean
    can_edit: boolean
    can_delete: boolean
    can_approve: boolean
    created_by: string | null
    created_at: string
}