// GENERATED FILE — do not hand-edit.
// Regenerate via: node scripts/generate-logo-raster.mjs
// Packs public/brand/kkkhane-k-logo.jpg into a 64x64 monochrome
// ESC/POS raster bitmap (GS v 0 format: row-major, MSB-first 1bpp, 1 = ink).

export const LOGO_WIDTH_BYTES = 8
export const LOGO_HEIGHT_DOTS = 64

const LOGO_BASE64 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AAAAAAAB//+AAAAAAAf//+AAAAAAH///+AAAAAA////8AAAAAH////4AAAAA/////wAAAAH/////gAAAA//////AAAAH/g/8B+AAAA/8D/gP8AAAD/wP8B/wAAAf/A/gP/gAAB/8D8B/+AAAP/wPgP/8AAA//A+A//wAAD/8DwH//AAAf/wOA//8AAB//AwH//4AAH/8CA///gAAf/wAH//+AAB//AA///4AAH/8AH///gAAf/wA///+AAB//AH///4AAH/8A+///gAAf/wDx//+AAB//AeD//4AAH/8DwP//AAAP/wfAf/8AAA//D+A//wAAD/8f8B//AAAH/z/4D/4AAAf/f/wH/gAAA////gP8AAAB////AfgAAAH/////+AAAAP/////wAAAAf////+AAAAA/////wAAAAB////+AAAAAD////wAAAAAD///8AAAAAAH///AAAAAAAD//wAAAAAAAB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='

export const LOGO_RASTER: Uint8Array = Uint8Array.from(atob(LOGO_BASE64), c => c.charCodeAt(0))
